// Code generated by MockGen. DO NOT EDIT.
// Source: repository_interface.go

// Package mock_oauth2 is a generated GoMock package.
package mock_oauth2

import (
	gomock "github.com/golang/mock/gomock"
	go_oauth2 "github.com/tsingsun/go-oauth2"
	reflect "reflect"
)

// MockAccessTokenRepositoryInterface is a mock of AccessTokenRepositoryInterface interface
type MockAccessTokenRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAccessTokenRepositoryInterfaceMockRecorder
}

// MockAccessTokenRepositoryInterfaceMockRecorder is the mock recorder for MockAccessTokenRepositoryInterface
type MockAccessTokenRepositoryInterfaceMockRecorder struct {
	mock *MockAccessTokenRepositoryInterface
}

// NewMockAccessTokenRepositoryInterface creates a new mock instance
func NewMockAccessTokenRepositoryInterface(ctrl *gomock.Controller) *MockAccessTokenRepositoryInterface {
	mock := &MockAccessTokenRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockAccessTokenRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAccessTokenRepositoryInterface) EXPECT() *MockAccessTokenRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetNewToken mocks base method
func (m *MockAccessTokenRepositoryInterface) GetNewToken(ce go_oauth2.ClientEntityInterface, scopes []go_oauth2.ScopeEntityInterface, userIdentifier string) go_oauth2.AccessTokenEntityInterface {
	ret := m.ctrl.Call(m, "GetNewToken", ce, scopes, userIdentifier)
	ret0, _ := ret[0].(go_oauth2.AccessTokenEntityInterface)
	return ret0
}

// GetNewToken indicates an expected call of GetNewToken
func (mr *MockAccessTokenRepositoryInterfaceMockRecorder) GetNewToken(ce, scopes, userIdentifier interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewToken", reflect.TypeOf((*MockAccessTokenRepositoryInterface)(nil).GetNewToken), ce, scopes, userIdentifier)
}

// PersistNewAccessToken mocks base method
func (m *MockAccessTokenRepositoryInterface) PersistNewAccessToken(accessTokenEntity go_oauth2.AccessTokenEntityInterface) bool {
	ret := m.ctrl.Call(m, "PersistNewAccessToken", accessTokenEntity)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PersistNewAccessToken indicates an expected call of PersistNewAccessToken
func (mr *MockAccessTokenRepositoryInterfaceMockRecorder) PersistNewAccessToken(accessTokenEntity interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistNewAccessToken", reflect.TypeOf((*MockAccessTokenRepositoryInterface)(nil).PersistNewAccessToken), accessTokenEntity)
}

// RevokeAccessToken mocks base method
func (m *MockAccessTokenRepositoryInterface) RevokeAccessToken(tokenId string) {
	m.ctrl.Call(m, "RevokeAccessToken", tokenId)
}

// RevokeAccessToken indicates an expected call of RevokeAccessToken
func (mr *MockAccessTokenRepositoryInterfaceMockRecorder) RevokeAccessToken(tokenId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAccessToken", reflect.TypeOf((*MockAccessTokenRepositoryInterface)(nil).RevokeAccessToken), tokenId)
}

// IsAccessTokenRevoked mocks base method
func (m *MockAccessTokenRepositoryInterface) IsAccessTokenRevoked(tokenId string) bool {
	ret := m.ctrl.Call(m, "IsAccessTokenRevoked", tokenId)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAccessTokenRevoked indicates an expected call of IsAccessTokenRevoked
func (mr *MockAccessTokenRepositoryInterfaceMockRecorder) IsAccessTokenRevoked(tokenId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAccessTokenRevoked", reflect.TypeOf((*MockAccessTokenRepositoryInterface)(nil).IsAccessTokenRevoked), tokenId)
}

// MockAuthCodeRepositoryInterface is a mock of AuthCodeRepositoryInterface interface
type MockAuthCodeRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthCodeRepositoryInterfaceMockRecorder
}

// MockAuthCodeRepositoryInterfaceMockRecorder is the mock recorder for MockAuthCodeRepositoryInterface
type MockAuthCodeRepositoryInterfaceMockRecorder struct {
	mock *MockAuthCodeRepositoryInterface
}

// NewMockAuthCodeRepositoryInterface creates a new mock instance
func NewMockAuthCodeRepositoryInterface(ctrl *gomock.Controller) *MockAuthCodeRepositoryInterface {
	mock := &MockAuthCodeRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockAuthCodeRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthCodeRepositoryInterface) EXPECT() *MockAuthCodeRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetNewAuthCode mocks base method
func (m *MockAuthCodeRepositoryInterface) GetNewAuthCode() go_oauth2.AuthCodeEntityInterface {
	ret := m.ctrl.Call(m, "GetNewAuthCode")
	ret0, _ := ret[0].(go_oauth2.AuthCodeEntityInterface)
	return ret0
}

// GetNewAuthCode indicates an expected call of GetNewAuthCode
func (mr *MockAuthCodeRepositoryInterfaceMockRecorder) GetNewAuthCode() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewAuthCode", reflect.TypeOf((*MockAuthCodeRepositoryInterface)(nil).GetNewAuthCode))
}

// PersistNewAuthCode mocks base method
func (m *MockAuthCodeRepositoryInterface) PersistNewAuthCode(authCodeEntity go_oauth2.AuthCodeEntityInterface) bool {
	ret := m.ctrl.Call(m, "PersistNewAuthCode", authCodeEntity)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PersistNewAuthCode indicates an expected call of PersistNewAuthCode
func (mr *MockAuthCodeRepositoryInterfaceMockRecorder) PersistNewAuthCode(authCodeEntity interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistNewAuthCode", reflect.TypeOf((*MockAuthCodeRepositoryInterface)(nil).PersistNewAuthCode), authCodeEntity)
}

// RevokeAuthCode mocks base method
func (m *MockAuthCodeRepositoryInterface) RevokeAuthCode(code string) {
	m.ctrl.Call(m, "RevokeAuthCode", code)
}

// RevokeAuthCode indicates an expected call of RevokeAuthCode
func (mr *MockAuthCodeRepositoryInterfaceMockRecorder) RevokeAuthCode(code interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAuthCode", reflect.TypeOf((*MockAuthCodeRepositoryInterface)(nil).RevokeAuthCode), code)
}

// IsAuthCodeRevoked mocks base method
func (m *MockAuthCodeRepositoryInterface) IsAuthCodeRevoked(code string) bool {
	ret := m.ctrl.Call(m, "IsAuthCodeRevoked", code)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAuthCodeRevoked indicates an expected call of IsAuthCodeRevoked
func (mr *MockAuthCodeRepositoryInterfaceMockRecorder) IsAuthCodeRevoked(code interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthCodeRevoked", reflect.TypeOf((*MockAuthCodeRepositoryInterface)(nil).IsAuthCodeRevoked), code)
}

// MockClientRepositoryInterface is a mock of ClientRepositoryInterface interface
type MockClientRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientRepositoryInterfaceMockRecorder
}

// MockClientRepositoryInterfaceMockRecorder is the mock recorder for MockClientRepositoryInterface
type MockClientRepositoryInterfaceMockRecorder struct {
	mock *MockClientRepositoryInterface
}

// NewMockClientRepositoryInterface creates a new mock instance
func NewMockClientRepositoryInterface(ctrl *gomock.Controller) *MockClientRepositoryInterface {
	mock := &MockClientRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockClientRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClientRepositoryInterface) EXPECT() *MockClientRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetClientEntity mocks base method
func (m *MockClientRepositoryInterface) GetClientEntity(clientIdentifier string, grantType go_oauth2.GrantType, clientSecret string, mustValidateSecret bool) go_oauth2.ClientEntityInterface {
	ret := m.ctrl.Call(m, "GetClientEntity", clientIdentifier, grantType, clientSecret, mustValidateSecret)
	ret0, _ := ret[0].(go_oauth2.ClientEntityInterface)
	return ret0
}

// GetClientEntity indicates an expected call of GetClientEntity
func (mr *MockClientRepositoryInterfaceMockRecorder) GetClientEntity(clientIdentifier, grantType, clientSecret, mustValidateSecret interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientEntity", reflect.TypeOf((*MockClientRepositoryInterface)(nil).GetClientEntity), clientIdentifier, grantType, clientSecret, mustValidateSecret)
}

// MockRefreshTokenRepositoryInterface is a mock of RefreshTokenRepositoryInterface interface
type MockRefreshTokenRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryInterfaceMockRecorder
}

// MockRefreshTokenRepositoryInterfaceMockRecorder is the mock recorder for MockRefreshTokenRepositoryInterface
type MockRefreshTokenRepositoryInterfaceMockRecorder struct {
	mock *MockRefreshTokenRepositoryInterface
}

// NewMockRefreshTokenRepositoryInterface creates a new mock instance
func NewMockRefreshTokenRepositoryInterface(ctrl *gomock.Controller) *MockRefreshTokenRepositoryInterface {
	mock := &MockRefreshTokenRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRefreshTokenRepositoryInterface) EXPECT() *MockRefreshTokenRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetNewRefreshToken mocks base method
func (m *MockRefreshTokenRepositoryInterface) GetNewRefreshToken() go_oauth2.RefreshTokenEntityInterface {
	ret := m.ctrl.Call(m, "GetNewRefreshToken")
	ret0, _ := ret[0].(go_oauth2.RefreshTokenEntityInterface)
	return ret0
}

// GetNewRefreshToken indicates an expected call of GetNewRefreshToken
func (mr *MockRefreshTokenRepositoryInterfaceMockRecorder) GetNewRefreshToken() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewRefreshToken", reflect.TypeOf((*MockRefreshTokenRepositoryInterface)(nil).GetNewRefreshToken))
}

// PersistNewRefreshToken mocks base method
func (m *MockRefreshTokenRepositoryInterface) PersistNewRefreshToken(refreshTokenEntity go_oauth2.RefreshTokenEntityInterface) bool {
	ret := m.ctrl.Call(m, "PersistNewRefreshToken", refreshTokenEntity)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PersistNewRefreshToken indicates an expected call of PersistNewRefreshToken
func (mr *MockRefreshTokenRepositoryInterfaceMockRecorder) PersistNewRefreshToken(refreshTokenEntity interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistNewRefreshToken", reflect.TypeOf((*MockRefreshTokenRepositoryInterface)(nil).PersistNewRefreshToken), refreshTokenEntity)
}

// RevokeRefreshToken mocks base method
func (m *MockRefreshTokenRepositoryInterface) RevokeRefreshToken(tokenId string) {
	m.ctrl.Call(m, "RevokeRefreshToken", tokenId)
}

// RevokeRefreshToken indicates an expected call of RevokeRefreshToken
func (mr *MockRefreshTokenRepositoryInterfaceMockRecorder) RevokeRefreshToken(tokenId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshToken", reflect.TypeOf((*MockRefreshTokenRepositoryInterface)(nil).RevokeRefreshToken), tokenId)
}

// IsRefreshTokenRevoked mocks base method
func (m *MockRefreshTokenRepositoryInterface) IsRefreshTokenRevoked(tokenId string) bool {
	ret := m.ctrl.Call(m, "IsRefreshTokenRevoked", tokenId)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRefreshTokenRevoked indicates an expected call of IsRefreshTokenRevoked
func (mr *MockRefreshTokenRepositoryInterfaceMockRecorder) IsRefreshTokenRevoked(tokenId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRefreshTokenRevoked", reflect.TypeOf((*MockRefreshTokenRepositoryInterface)(nil).IsRefreshTokenRevoked), tokenId)
}

// MockScopeRepositoryInterface is a mock of ScopeRepositoryInterface interface
type MockScopeRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockScopeRepositoryInterfaceMockRecorder
}

// MockScopeRepositoryInterfaceMockRecorder is the mock recorder for MockScopeRepositoryInterface
type MockScopeRepositoryInterfaceMockRecorder struct {
	mock *MockScopeRepositoryInterface
}

// NewMockScopeRepositoryInterface creates a new mock instance
func NewMockScopeRepositoryInterface(ctrl *gomock.Controller) *MockScopeRepositoryInterface {
	mock := &MockScopeRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockScopeRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockScopeRepositoryInterface) EXPECT() *MockScopeRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetScopeEntityByIdentifier mocks base method
func (m *MockScopeRepositoryInterface) GetScopeEntityByIdentifier(identifier string) go_oauth2.ScopeEntityInterface {
	ret := m.ctrl.Call(m, "GetScopeEntityByIdentifier", identifier)
	ret0, _ := ret[0].(go_oauth2.ScopeEntityInterface)
	return ret0
}

// GetScopeEntityByIdentifier indicates an expected call of GetScopeEntityByIdentifier
func (mr *MockScopeRepositoryInterfaceMockRecorder) GetScopeEntityByIdentifier(identifier interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScopeEntityByIdentifier", reflect.TypeOf((*MockScopeRepositoryInterface)(nil).GetScopeEntityByIdentifier), identifier)
}

// FinalizeScopes mocks base method
func (m *MockScopeRepositoryInterface) FinalizeScopes(scopes []go_oauth2.ScopeEntityInterface, grantType go_oauth2.GrantType, clientEntity go_oauth2.ClientEntityInterface, userIdentifier string) []go_oauth2.ScopeEntityInterface {
	ret := m.ctrl.Call(m, "FinalizeScopes", scopes, grantType, clientEntity, userIdentifier)
	ret0, _ := ret[0].([]go_oauth2.ScopeEntityInterface)
	return ret0
}

// FinalizeScopes indicates an expected call of FinalizeScopes
func (mr *MockScopeRepositoryInterfaceMockRecorder) FinalizeScopes(scopes, grantType, clientEntity, userIdentifier interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeScopes", reflect.TypeOf((*MockScopeRepositoryInterface)(nil).FinalizeScopes), scopes, grantType, clientEntity, userIdentifier)
}

// MockUserRepositoryInterface is a mock of UserRepositoryInterface interface
type MockUserRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryInterfaceMockRecorder
}

// MockUserRepositoryInterfaceMockRecorder is the mock recorder for MockUserRepositoryInterface
type MockUserRepositoryInterfaceMockRecorder struct {
	mock *MockUserRepositoryInterface
}

// NewMockUserRepositoryInterface creates a new mock instance
func NewMockUserRepositoryInterface(ctrl *gomock.Controller) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetUserEntityByUserCredentials mocks base method
func (m *MockUserRepositoryInterface) GetUserEntityByUserCredentials(username, password, grantType string, clientEntity go_oauth2.ClientEntityInterface) go_oauth2.UserEntityInterface {
	ret := m.ctrl.Call(m, "GetUserEntityByUserCredentials", username, password, grantType, clientEntity)
	ret0, _ := ret[0].(go_oauth2.UserEntityInterface)
	return ret0
}

// GetUserEntityByUserCredentials indicates an expected call of GetUserEntityByUserCredentials
func (mr *MockUserRepositoryInterfaceMockRecorder) GetUserEntityByUserCredentials(username, password, grantType, clientEntity interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserEntityByUserCredentials", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetUserEntityByUserCredentials), username, password, grantType, clientEntity)
}
